# Generated by Django 4.2.7 on 2023-11-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.PositiveIntegerField()),
                ('customer', models.TextField()),
                ('age', models.PositiveIntegerField()),
                ('gender', models.TextField()),
                ('zipcodeOri', models.TextField()),
                ('merchant', models.PositiveIntegerField()),
                ('zipMerchant', models.TextField()),
                ('category', models.TextField()),
                ('amount', models.PositiveIntegerField()),
                ('fraud', models.CharField(choices=[('suspect', 'Сомнительный'), ('approved', 'Одобренный')], default=('suspect', 'Сомнительный'), max_length=20, verbose_name='Статус')),
            ],
            options={
                'verbose_name': '"Транзакция"',
                'verbose_name_plural': 'Транзакции',
            },
        ),
    ]
