# Generated by Django 4.2.7 on 2023-11-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_transactions_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='is_denied',
            field=models.BooleanField(default=False),
        ),
    ]
